database:
  host: 1Panel-mysql-TUuu
  port: 3306
  dbname: app_db
  user: test
  password: D7p6ZkcJRMynPfCy

redis:
  host: 1Panel-redis-dpZp
  port: 6379
  password: 32wB6ejWwb78cPKT
  db: 0

jwt:
  secret: se123abc456
  expire_time: 7200       # access_token 过期时间，单位：秒，默认 2 小时
  refresh_expire_time: 604800  # refresh_token 过期时间，单位：秒，默认 7 天

server:
  port: 8080